# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20181130_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_sn',
            field=models.CharField(max_length=64, unique=True, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='goods_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop_SKU', verbose_name='订单商品SKUID'),
        ),
    ]
