# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 15:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20181128_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('hcity', models.CharField(max_length=50, verbose_name='省')),
                ('hproper', models.CharField(max_length=50, verbose_name='市')),
                ('harea', models.CharField(max_length=50, verbose_name='区')),
                ('detail', models.CharField(max_length=255, verbose_name='详细地址')),
                ('username', models.CharField(max_length=50, verbose_name='收货人姓名')),
                ('telephone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号格式错误')], verbose_name='收货人手机号')),
                ('isDefault', models.BooleanField(default=False, verbose_name='是否为默认地址')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='user.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户地址管理',
                'verbose_name_plural': '用户地址管理',
                'db_table': 'address',
            },
        ),
    ]
