# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181123_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_sku',
            name='unit_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Unit', verbose_name='单位'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='active_sku',
            name='sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop_SKU', verbose_name='商品SKUID'),
        ),
        migrations.AlterField(
            model_name='active_sku',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Active_zone', verbose_name='专区ID'),
        ),
        migrations.AlterField(
            model_name='lunbo',
            name='image_address',
            field=models.ImageField(upload_to='shop_lunbo/%Y%m/%d', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='lunbo',
            name='sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop_SKU', verbose_name='商品SKUID'),
        ),
        migrations.AlterField(
            model_name='shop_album',
            name='image_address',
            field=models.ImageField(upload_to='shop_album/%Y%m/%d', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='shop_album',
            name='sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop_SKU', verbose_name='商品SKUID'),
        ),
        migrations.AlterField(
            model_name='shop_sku',
            name='sku_address',
            field=models.ImageField(upload_to='shop_SKU/%Y%m/%d', verbose_name='商品LOGO地址'),
        ),
        migrations.AlterField(
            model_name='shop_sku',
            name='sort_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop_sort', verbose_name='商品分类id'),
        ),
        migrations.AlterField(
            model_name='shop_sku',
            name='spu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop_SPU', verbose_name='商品SPUid'),
        ),
    ]
