# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181119_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=11),
        ),
    ]
